# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Description'),
            preserve_default=False,
        ),
    ]
